version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8013:8013"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul-server
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: springboot-app
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
      - consul-server
      - script_before_run

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  consul-server:
    image: hashicorp/consul:1.12.2
    container_name: consul-server
    restart: unless-stopped
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul_data:/consul/data

  script_before_run:
    image: curlimages/curl:7.87.0
    container_name: script_before_run
    depends_on:
      - consul-server
    entrypoint: >
      sh -c "
      sleep 3 &&
      curl --request PUT --data 'jdbc:mysql://db:3306/mydb' http://consul-server:8500/v1/kv/config/springboot-app/spring.datasource.url &&
      curl --request PUT --data 'user' http://consul-server:8500/v1/kv/config/springboot-app/spring.datasource.username &&
      curl --request PUT --data 'password' http://consul-server:8500/v1/kv/config/springboot-app/spring.datasource.password
      "

volumes:
  db-data:
  consul_data:
